### post a new user
POST http://localhost:4000/test/users HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "user 7",
  "email": "u7@gmail.com",
  "password": "1234"
}

### get all user
GET http://localhost:4000/test/users HTTP/1.1

### get specific user
GET http://localhost:4000/test/users/63360379061e5b283644f1cd HTTP/1.1


### update an user
PUT http://localhost:4000/test/users/63360379061e5b283644f1cd HTTP/1.1
Content-Type: application/json

{
  "name": "Juan front",
  "email": "j@juan.com",
  "password": "1234"
}

### Delete an user
DELETE http://localhost:4000/test/users/6334d7285fd8cb18d0a2a3d3 HTTP/1.1


### Post balance income user
POST http://localhost:4000/test/balance HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "user": "63360379061e5b283644f1cd",
  "activity": "Salario",
  "category": "El play5",
  "amount": "1000",
  "balance_type": "income"
}

### Get user income
GET http://localhost:4000/test/balance/63360379061e5b283644f1cd HTTP/1.1


### Delete an income
DELETE http://localhost:4000/test/balance/634c169912ff4c38c0cd1d69 HTTP/1.1